# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Nota(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, dni_alumno: int=None, id_asignatura: int=None, nota: float=None):
        """
        Nota - a model defined in Swagger

        :param dni_alumno: The dni_alumno of this Nota.
        :type dni_alumno: int
        :param id_asignatura: The id_asignatura of this Nota.
        :type id_asignatura: int
        :param nota: The nota of this Nota.
        :type nota: float
        """
        self.swagger_types = {
            'dni_alumno': int,
            'id_asignatura': int,
            'nota': float
        }

        self.attribute_map = {
            'dni_alumno': 'dniAlumno',
            'id_asignatura': 'idAsignatura',
            'nota': 'nota'
        }

        self._dni_alumno = dni_alumno
        self._id_asignatura = id_asignatura
        self._nota = nota

    @classmethod
    def from_dict(cls, dikt) -> 'Nota':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Nota of this Nota.
        :rtype: Nota
        """
        return deserialize_model(dikt, cls)

    @property
    def dni_alumno(self) -> int:
        """
        Gets the dni_alumno of this Nota.

        :return: The dni_alumno of this Nota.
        :rtype: int
        """
        return self._dni_alumno

    @dni_alumno.setter
    def dni_alumno(self, dni_alumno: int):
        """
        Sets the dni_alumno of this Nota.

        :param dni_alumno: The dni_alumno of this Nota.
        :type dni_alumno: int
        """

        self._dni_alumno = dni_alumno

    @property
    def id_asignatura(self) -> int:
        """
        Gets the id_asignatura of this Nota.

        :return: The id_asignatura of this Nota.
        :rtype: int
        """
        return self._id_asignatura

    @id_asignatura.setter
    def id_asignatura(self, id_asignatura: int):
        """
        Sets the id_asignatura of this Nota.

        :param id_asignatura: The id_asignatura of this Nota.
        :type id_asignatura: int
        """

        self._id_asignatura = id_asignatura

    @property
    def nota(self) -> float:
        """
        Gets the nota of this Nota.

        :return: The nota of this Nota.
        :rtype: float
        """
        return self._nota

    @nota.setter
    def nota(self, nota: float):
        """
        Sets the nota of this Nota.

        :param nota: The nota of this Nota.
        :type nota: float
        """

        self._nota = nota

